apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - site-deployment.yaml
  - ingress.yaml
  - cronjob.yaml
  - wyoming-media-discovery-cronjob.yaml
  - wyoming-transcription-cronjob.yaml
  - wyoming-reasoning-cronjob.yaml
  - servicemonitor.yaml
  - monitoring/keeping-law-simple-traffic-dashboard.yaml
