apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keeping-law-simple-qa-data
  namespace: keeping-law-simple
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
