apiVersion: v1
kind: Service
metadata:
  name: keeping-law-simple-qa-web
  namespace: keeping-law-simple
  labels:
    app: keeping-law-simple-qa-web
    app.kubernetes.io/name: keeping-law-simple-qa
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.104.22
  selector:
    app: keeping-law-simple-qa-web
  ports:
    - name: http
      port: 80
      targetPort: http
