apiVersion: v1
kind: Service
metadata:
  name: keeping-law-simple-web
  namespace: keeping-law-simple
  labels:
    app: keeping-law-simple-web
    app.kubernetes.io/name: keeping-law-simple
spec:
  selector:
    app: keeping-law-simple-web
  ports:
    - name: http
      port: 80
      targetPort: http
