from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Jurisdiction:
    slug: str
    name: str
    kind: str
    state_code: str | None
    coverage_status: str
    coverage_note: str
    description: str
    source_name: str
    source_url: str | None


JURISDICTIONS = (
    Jurisdiction(
        slug="wyoming",
        name="Wyoming",
        kind="state",
        state_code="wy",
        coverage_status="live",
        coverage_note="Available",
        description="Official Wyoming bill text, status, plain English summaries, and bill-to-bill review notes.",
        source_name="Wyoming Legislature",
        source_url="https://www.wyoleg.gov",
    ),
    Jurisdiction(
        slug="alabama",
        name="Alabama",
        kind="state",
        state_code="al",
        coverage_status="live",
        coverage_note="Available",
        description="Official Alabama bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="Alabama Legislature",
        source_url="https://alison.legislature.state.al.us",
    ),
    Jurisdiction(
        slug="alaska",
        name="Alaska",
        kind="state",
        state_code="ak",
        coverage_status="live",
        coverage_note="Available",
        description="Official Alaska bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="Alaska State Legislature",
        source_url="https://www.akleg.gov",
    ),
    Jurisdiction(
        slug="kansas",
        name="Kansas",
        kind="state",
        state_code="ks",
        coverage_status="live",
        coverage_note="Available",
        description="Official Kansas bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="Kansas State Legislature",
        source_url="https://www.kslegislature.gov",
    ),
    Jurisdiction(
        slug="kentucky",
        name="Kentucky",
        kind="state",
        state_code="ky",
        coverage_status="live",
        coverage_note="Available",
        description="Official Kentucky bill text, status, plain English summaries, and amendment notes pulled from the Legislature's session record.",
        source_name="Kentucky Legislative Research Commission",
        source_url="https://legislature.ky.gov/Legislation/Pages/default.aspx",
    ),
    Jurisdiction(
        slug="louisiana",
        name="Louisiana",
        kind="state",
        state_code="la",
        coverage_status="live",
        coverage_note="Available",
        description="Official Louisiana bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own bill tracker.",
        source_name="Louisiana State Legislature",
        source_url="https://legis.la.gov/legis/home.aspx",
    ),
    Jurisdiction(
        slug="maine",
        name="Maine",
        kind="state",
        state_code="me",
        coverage_status="live",
        coverage_note="Available",
        description="Official Maine bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own bill directory and chamber status pages.",
        source_name="Maine State Legislature",
        source_url="https://legislature.maine.gov",
    ),
    Jurisdiction(
        slug="arizona",
        name="Arizona",
        kind="state",
        state_code="az",
        coverage_status="live",
        coverage_note="Available",
        description="Official Arizona bill text, status, plain English summaries, and amendment notes tied back to the Legislature's bill status system.",
        source_name="Arizona State Legislature",
        source_url="https://www.azleg.gov",
    ),
    Jurisdiction(
        slug="arkansas",
        name="Arkansas",
        kind="state",
        state_code="ar",
        coverage_status="live",
        coverage_note="Available",
        description="Official Arkansas bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="Arkansas State Legislature",
        source_url="https://www.arkleg.state.ar.us",
    ),
    Jurisdiction(
        slug="california",
        name="California",
        kind="state",
        state_code="ca",
        coverage_status="live",
        coverage_note="Available",
        description="Official California bill text, status, plain English summaries, and history notes pulled from the Legislature's bill information system.",
        source_name="California Legislative Information",
        source_url="https://leginfo.legislature.ca.gov",
    ),
    Jurisdiction(
        slug="delaware",
        name="Delaware",
        kind="state",
        state_code="de",
        coverage_status="live",
        coverage_note="Available",
        description="Official Delaware bill text, status, plain English summaries, and amendment notes tied back to the General Assembly's own records.",
        source_name="Delaware General Assembly",
        source_url="https://legis.delaware.gov",
    ),
    Jurisdiction(
        slug="district-of-columbia",
        name="District of Columbia",
        kind="state",
        state_code="dc",
        coverage_status="live",
        coverage_note="Available",
        description="Official D.C. Council bill text, status, plain English summaries, and action history pulled from the Legislative Information Management System.",
        source_name="Council of the District of Columbia LIMS",
        source_url="https://lims.dccouncil.gov",
    ),
    Jurisdiction(
        slug="georgia",
        name="Georgia",
        kind="state",
        state_code="ga",
        coverage_status="live",
        coverage_note="Available",
        description="Official Georgia bill text, status, plain English summaries, and vote history tied back to the General Assembly's records.",
        source_name="Georgia General Assembly",
        source_url="https://www.legis.ga.gov",
    ),
    Jurisdiction(
        slug="hawaii",
        name="Hawaii",
        kind="state",
        state_code="hi",
        coverage_status="live",
        coverage_note="Available",
        description="Official Hawaii measure text, status, plain English summaries, and version notes pulled from the Legislature's own data site.",
        source_name="Hawaii State Legislature",
        source_url="https://data.capitol.hawaii.gov",
    ),
    Jurisdiction(
        slug="florida",
        name="Florida",
        kind="state",
        state_code="fl",
        coverage_status="live",
        coverage_note="Available",
        description="Official Florida bill text, status, plain English summaries, and amendment notes pulled from the Legislature's bill tracker.",
        source_name="The Florida Senate and Florida House of Representatives",
        source_url="https://www.flsenate.gov/Session/Bills",
    ),
    Jurisdiction(
        slug="idaho",
        name="Idaho",
        kind="state",
        state_code="id",
        coverage_status="live",
        coverage_note="Available",
        description="Official Idaho bill text, status, plain English summaries, and session-law notes tied back to the Legislature's own records.",
        source_name="Idaho State Legislature",
        source_url="https://legislature.idaho.gov/sessioninfo/2026/legislation/",
    ),
    Jurisdiction(
        slug="illinois",
        name="Illinois",
        kind="state",
        state_code="il",
        coverage_status="live",
        coverage_note="Available",
        description="Official Illinois bill text, status, plain English summaries, and amendment notes tied back to the General Assembly's own bill status pages.",
        source_name="Illinois General Assembly",
        source_url="https://www.ilga.gov/legislation",
    ),
    Jurisdiction(
        slug="indiana",
        name="Indiana",
        kind="state",
        state_code="in",
        coverage_status="live",
        coverage_note="Available",
        description="Indiana bill text, status, plain English summaries, and version history using a temporary fallback while the public Indiana bill site is being repaired.",
        source_name="Indiana General Assembly",
        source_url="https://iga.in.gov",
    ),
    Jurisdiction(
        slug="north-dakota",
        name="North Dakota",
        kind="state",
        state_code="nd",
        coverage_status="live",
        coverage_note="Available",
        description="Official North Dakota bill text, status, plain English summaries, and amendment notes pulled from the Legislature's measure directory.",
        source_name="North Dakota Legislative Branch",
        source_url="https://ndlegis.gov/assembly/69-2025/regular/documents/bill-download.html",
    ),
    Jurisdiction(
        slug="iowa",
        name="Iowa",
        kind="state",
        state_code="ia",
        coverage_status="live",
        coverage_note="Available",
        description="Official Iowa bill text, status, plain English summaries, and amendment notes tied back to the Legislature's bill book.",
        source_name="Iowa Legislature",
        source_url="https://www.legis.iowa.gov",
    ),
    Jurisdiction(
        slug="maryland",
        name="Maryland",
        kind="state",
        state_code="md",
        coverage_status="live",
        coverage_note="Available",
        description="Official Maryland bill text, status, plain English summaries, and amendment notes tied back to the General Assembly's own records.",
        source_name="Maryland General Assembly",
        source_url="https://mgaleg.maryland.gov",
    ),
    Jurisdiction(
        slug="massachusetts",
        name="Massachusetts",
        kind="state",
        state_code="ma",
        coverage_status="live",
        coverage_note="Available",
        description="Official Massachusetts bill text, status, plain English summaries, and bill-history notes tied back to the General Court's own records.",
        source_name="The General Court of the Commonwealth of Massachusetts",
        source_url="https://malegislature.gov",
    ),
    Jurisdiction(
        slug="michigan",
        name="Michigan",
        kind="state",
        state_code="mi",
        coverage_status="live",
        coverage_note="Available",
        description="Official Michigan bill text, status, plain English summaries, and document history tied back to the Legislature's bill tracker.",
        source_name="Michigan Legislature",
        source_url="https://www.legislature.mi.gov/Bills/Bills",
    ),
    Jurisdiction(
        slug="washington",
        name="Washington",
        kind="state",
        state_code="wa",
        coverage_status="live",
        coverage_note="Available",
        description="Official Washington bill text, status, plain English summaries, and amendment notes pulled from the Legislature's web services and public bill pages.",
        source_name="Washington State Legislature",
        source_url="https://leg.wa.gov/bills-meetings-and-session/bills/",
    ),
    Jurisdiction(
        slug="north-carolina",
        name="North Carolina",
        kind="state",
        state_code="nc",
        coverage_status="live",
        coverage_note="Available",
        description="Official North Carolina bill pages, summaries, plain English breakdowns, and committee-change notes tied back to the General Assembly's own records.",
        source_name="North Carolina General Assembly",
        source_url="https://www.ncleg.gov",
    ),
    Jurisdiction(
        slug="rhode-island",
        name="Rhode Island",
        kind="state",
        state_code="ri",
        coverage_status="live",
        coverage_note="Available",
        description="Official Rhode Island bill text, status, plain English summaries, and amendment notes tied back to the General Assembly's own records.",
        source_name="Rhode Island General Assembly",
        source_url="https://www.rilegislature.gov/pages/legislation.aspx",
    ),
    Jurisdiction(
        slug="minnesota",
        name="Minnesota",
        kind="state",
        state_code="mn",
        coverage_status="live",
        coverage_note="Available",
        description="Official Minnesota bill text, status, plain English summaries, and version history pulled from the Revisor's bill tracker.",
        source_name="Minnesota Office of the Revisor of Statutes",
        source_url="https://www.revisor.mn.gov",
    ),
    Jurisdiction(
        slug="missouri",
        name="Missouri",
        kind="state",
        state_code="mo",
        coverage_status="live",
        coverage_note="Available",
        description="Official Missouri bill text, status, plain English summaries, and amendment notes pulled from the House and Senate bill trackers.",
        source_name="Missouri House of Representatives and Missouri Senate",
        source_url="https://house.mo.gov/billcentral.aspx",
    ),
    Jurisdiction(
        slug="montana",
        name="Montana",
        kind="state",
        state_code="mt",
        coverage_status="live",
        coverage_note="Available",
        description="Official Montana bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="Montana Legislature",
        source_url="https://leg.mt.gov",
    ),
    Jurisdiction(
        slug="nevada",
        name="Nevada",
        kind="state",
        state_code="nv",
        coverage_status="live",
        coverage_note="Available",
        description="Official Nevada bill text, status, plain English summaries, and amendment notes tied back to NELIS bill pages.",
        source_name="Nevada Electronic Legislative Information System",
        source_url="https://www.leg.state.nv.us",
    ),
    Jurisdiction(
        slug="new-jersey",
        name="New Jersey",
        kind="state",
        state_code="nj",
        coverage_status="live",
        coverage_note="Available",
        description="Official New Jersey bill text, status, plain English summaries, and action-history notes pulled from the Legislature's bill search APIs.",
        source_name="New Jersey Legislature",
        source_url="https://www.njleg.state.nj.us",
    ),
    Jurisdiction(
        slug="new-hampshire",
        name="New Hampshire",
        kind="state",
        state_code="nh",
        coverage_status="live",
        coverage_note="Available",
        description="Official New Hampshire bill text, status, plain English summaries, and docket notes tied back to the General Court's bill status system.",
        source_name="New Hampshire General Court",
        source_url="https://gc.nh.gov/bill_status/legacy/bs2016/default.aspx",
    ),
    Jurisdiction(
        slug="ohio",
        name="Ohio",
        kind="state",
        state_code="oh",
        coverage_status="live",
        coverage_note="Available",
        description="Official Ohio bill text, status, plain English summaries, and amendment notes tied back to the Legislature's SOLAR records.",
        source_name="Ohio Legislature",
        source_url="https://www.legislature.ohio.gov/legislation/search",
    ),
    Jurisdiction(
        slug="oklahoma",
        name="Oklahoma",
        kind="state",
        state_code="ok",
        coverage_status="live",
        coverage_note="Available",
        description="Official Oklahoma bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own bill tracker.",
        source_name="Oklahoma Legislature",
        source_url="https://www.oklegislature.gov",
    ),
    Jurisdiction(
        slug="oregon",
        name="Oregon",
        kind="state",
        state_code="or",
        coverage_status="live",
        coverage_note="Available",
        description="Official Oregon measure text, status, plain English summaries, and history notes pulled from OLIS.",
        source_name="Oregon Legislative Information System",
        source_url="https://olis.oregonlegislature.gov/liz/2025R1/Measures/list",
    ),
    Jurisdiction(
        slug="pennsylvania",
        name="Pennsylvania",
        kind="state",
        state_code="pa",
        coverage_status="live",
        coverage_note="Available",
        description="Official Pennsylvania bill text, status, plain English summaries, and amendment notes pulled from the General Assembly's own bill-history export.",
        source_name="Pennsylvania General Assembly",
        source_url="https://www.palegis.us/legislation/bills",
    ),
    Jurisdiction(
        slug="west-virginia",
        name="West Virginia",
        kind="state",
        state_code="wv",
        coverage_status="live",
        coverage_note="Available",
        description="Official West Virginia bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="West Virginia Legislature",
        source_url="https://www.wvlegislature.gov",
    ),
    Jurisdiction(
        slug="colorado",
        name="Colorado",
        kind="state",
        state_code="co",
        coverage_status="live",
        coverage_note="Available",
        description="Official Colorado bill text, status, plain English summaries, and amendment notes tied back to the source.",
        source_name="Colorado General Assembly",
        source_url="https://leg.colorado.gov",
    ),
    Jurisdiction(
        slug="connecticut",
        name="Connecticut",
        kind="state",
        state_code="ct",
        coverage_status="live",
        coverage_note="Available",
        description="Official Connecticut bill text, status, plain English summaries, and amendment notes pulled from the General Assembly's bill tracker.",
        source_name="Connecticut General Assembly",
        source_url="https://www.cga.ct.gov",
    ),
    Jurisdiction(
        slug="nebraska",
        name="Nebraska",
        kind="state",
        state_code="ne",
        coverage_status="live",
        coverage_note="Available",
        description="Official Nebraska bill text, status, and plain English summaries tied back to the Legislature's bill room and action history.",
        source_name="Nebraska Legislature",
        source_url="https://nebraskalegislature.gov",
    ),
    Jurisdiction(
        slug="south-carolina",
        name="South Carolina",
        kind="state",
        state_code="sc",
        coverage_status="live",
        coverage_note="Available",
        description="Official South Carolina bill text, status, and plain English summaries tied back to the General Assembly's introduction and bill pages.",
        source_name="South Carolina Legislature",
        source_url="https://www.scstatehouse.gov",
    ),
    Jurisdiction(
        slug="south-dakota",
        name="South Dakota",
        kind="state",
        state_code="sd",
        coverage_status="live",
        coverage_note="Available",
        description="Official South Dakota bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own APIs and document service.",
        source_name="South Dakota Legislature",
        source_url="https://sdlegislature.gov",
    ),
    Jurisdiction(
        slug="virginia",
        name="Virginia",
        kind="state",
        state_code="va",
        coverage_status="live",
        coverage_note="Available",
        description="Official Virginia bill text, status, plain English summaries, and amendment notes pulled from the LIS bill tracker.",
        source_name="Virginia Legislative Information System",
        source_url="https://lis.virginia.gov",
    ),
    Jurisdiction(
        slug="wisconsin",
        name="Wisconsin",
        kind="state",
        state_code="wi",
        coverage_status="live",
        coverage_note="Available",
        description="Official Wisconsin bill text, status, plain English summaries, and session-history notes tied back to the Legislature's own document system.",
        source_name="Wisconsin Legislature",
        source_url="https://docs.legis.wisconsin.gov",
    ),
    Jurisdiction(
        slug="tennessee",
        name="Tennessee",
        kind="state",
        state_code="tn",
        coverage_status="live",
        coverage_note="Available",
        description="Official Tennessee bill text, status, plain English summaries, and amendment notes pulled from the General Assembly site.",
        source_name="Tennessee General Assembly",
        source_url="https://wapp.capitol.tn.gov",
    ),
    Jurisdiction(
        slug="texas",
        name="Texas",
        kind="state",
        state_code="tx",
        coverage_status="live",
        coverage_note="Available",
        description="Official Texas bill text, status, plain English summaries, and bill history pulled from Texas Legislature Online.",
        source_name="Texas Legislature Online",
        source_url="https://capitol.texas.gov",
    ),
    Jurisdiction(
        slug="mississippi",
        name="Mississippi",
        kind="state",
        state_code="ms",
        coverage_status="live",
        coverage_note="Available",
        description="Official Mississippi bill text, status, and plain English summaries tied to the Legislature's bill status system.",
        source_name="Mississippi Legislative Bill Status System",
        source_url="https://billstatus.ls.state.ms.us",
    ),
    Jurisdiction(
        slug="new-mexico",
        name="New Mexico",
        kind="state",
        state_code="nm",
        coverage_status="live",
        coverage_note="Available",
        description="Official New Mexico bill text, status, plain English summaries, and amendment notes tied back to the Legislature's own records.",
        source_name="New Mexico Legislature",
        source_url="https://www.nmlegis.gov",
    ),
    Jurisdiction(
        slug="new-york",
        name="New York",
        kind="state",
        state_code="ny",
        coverage_status="live",
        coverage_note="Available",
        description="Official New York bill text, status, plain English summaries, and action history pulled from the New York State Senate's Open Legislation API.",
        source_name="New York State Senate Open Legislation API",
        source_url="https://legislation.nysenate.gov/static/docs/html/index.html",
    ),
    Jurisdiction(
        slug="vermont",
        name="Vermont",
        kind="state",
        state_code="vt",
        coverage_status="live",
        coverage_note="Available",
        description="Official Vermont bill text, status, plain English summaries, and bill history tied back to the General Assembly's own records.",
        source_name="Vermont General Assembly",
        source_url="https://legislature.vermont.gov",
    ),
    Jurisdiction(
        slug="utah",
        name="Utah",
        kind="state",
        state_code="ut",
        coverage_status="live",
        coverage_note="Available",
        description="Official Utah bill text, status, plain English summaries, and version history pulled from the Legislature's bill system.",
        source_name="Utah State Legislature",
        source_url="https://le.utah.gov",
    ),
    Jurisdiction(
        slug="federal",
        name="Federal",
        kind="federal",
        state_code="us",
        coverage_status="live",
        coverage_note="Available",
        description="Recent federal bills from Congress with official text, current status, and plain English summaries checked against the source.",
        source_name="Congress.gov",
        source_url="https://www.congress.gov",
    ),
)


def list_jurisdictions() -> list[Jurisdiction]:
    return sorted(
        JURISDICTIONS,
        key=lambda jurisdiction: (
            0 if jurisdiction.kind == "state" else 1,
            jurisdiction.name.lower(),
        ),
    )


def get_jurisdiction(slug: str) -> Jurisdiction | None:
    normalized = slug.strip().lower()
    for jurisdiction in JURISDICTIONS:
        if jurisdiction.slug == normalized:
            return jurisdiction
    return None


def get_state_jurisdiction(slug: str) -> Jurisdiction | None:
    jurisdiction = get_jurisdiction(slug)
    if jurisdiction is None or jurisdiction.kind != "state":
        return None
    return jurisdiction


def get_jurisdiction_by_state_code(state_code: str | None) -> Jurisdiction | None:
    normalized = (state_code or "").strip().lower()
    if not normalized:
        return None
    for jurisdiction in JURISDICTIONS:
        if (jurisdiction.state_code or "").strip().lower() == normalized:
            return jurisdiction
    return None


def jurisdiction_href(jurisdiction: Jurisdiction) -> str:
    if jurisdiction.kind == "state":
        return f"/states/{jurisdiction.slug}"
    return "/federal"
